version: "3"
services:
  symfony-roadrunner:
    build:
      dockerfile: Dockerfile.local
      context: .
    #   args:
    #     - EXPORTED_USER=${EXPORTED_USER}
    #     - EXPORTED_GROUP=${EXPORTED_GROUP}
    ports:
      - "9999:8080"
    env_file: .env
    environment:
      - APP_EXECUTE_MIGRATIONS=true
      - XDEBUG_ACTIVATED=true
    volumes:
      - ./app:/var/www/app
